# Generated by Django 4.1 on 2022-08-25 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_creator_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('music_choice', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-binary', 'Non-binary'), ('Prefer Not To Say', 'Prefer Not To Say')], default='Prefer Not To Say', max_length=250)),
                ('gender_custom', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=4, max_digits=6, max_length=10)),
                ('height', models.DecimalField(decimal_places=4, max_digits=6, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnicity')),
            ],
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
