# Generated by Django 4.1 on 2022-08-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_status_talent_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.talent')),
                ('role', models.ForeignKey(default='Role', on_delete=django.db.models.deletion.CASCADE, to='main.role')),
            ],
        ),
    ]
