# Generated by Django 4.1 on 2022-08-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
