# Generated by Django 4.1 on 2022-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='Role', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='talent_height',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='talent_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, max_length=10),
        ),
    ]
