# Generated by Django 4.1 on 2022-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_talent_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='height',
            field=models.DecimalField(decimal_places=4, max_digits=6, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=6, max_length=10, null=True),
        ),
    ]
