# Generated by Django 4.1 on 2022-08-25 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_company_talent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talent',
            old_name='status',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='gender_custom',
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_age', models.IntegerField()),
                ('talent_gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-binary', 'Non-binary'), ('Prefer Not To Say', 'Prefer Not To Say')], default='Prefer Not To Say', max_length=250)),
                ('talent_weight', models.DecimalField(decimal_places=4, max_digits=6, max_length=10)),
                ('talent_height', models.DecimalField(decimal_places=4, max_digits=6, max_length=10)),
                ('talent_ethnicity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('roles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ethnicity')),
            ],
        ),
    ]
