# Generated by Django 4.1 on 2022-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_role_role_name_alter_role_talent_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='Role Name', max_length=255),
        ),
    ]
