# Generated by Django 4.1 on 2022-08-25 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_role_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='roles',
            new_name='ethnicity',
        ),
        migrations.AddField(
            model_name='project',
            name='role_name',
            field=models.ForeignKey(default='Role Name', on_delete=django.db.models.deletion.CASCADE, to='main.role'),
        ),
        migrations.AddField(
            model_name='talent',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.talent')),
                ('role_name', models.ForeignKey(default='Role Name', on_delete=django.db.models.deletion.CASCADE, to='main.role')),
            ],
        ),
    ]
