# Generated by Django 4.1 on 2022-08-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_roles_project_ethnicity_project_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='role_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.role'),
        ),
    ]
