# Generated by Django 4.1 on 2022-08-25 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_roles_project_ethnicity_project_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='role_name',
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.ForeignKey(default='Role', on_delete=django.db.models.deletion.CASCADE, to='main.role'),
        ),
    ]
