# Generated by Django 4.1 on 2022-08-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ethnicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ethnicity'),
        ),
    ]
