# Generated by Django 4.1 on 2022-08-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_application_role_name_application_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
